import {
  ShieldCheck, BadgeCheck, Video, ClipboardList, Building2, Quote,
  ArrowRightLeft, Languages, MapPin, Clock, CheckCircle2, Play,
} from 'lucide-react'
import Avatar from '@/components/Avatar'

/**
 * The NetWorthy Record — the CV reinvented as the receipt of a human
 * connection. Verification-first: it leads with what independent humans
 * confirmed, and demotes chronology to an appendix labeled "context,
 * not credentials". Generated by the platform, never self-reported.
 */

export type RecordData = {
  match: {
    id: number
    stage: string
    role: string
    company: string
    connectionRating: number | null
  }
  talent: {
    id: number
    name: string
    role: string
    tagline: string
    story: string
    origin: string
    yearsInNL: number
    languages: string[]
    gradient: string
  }
  verified: {
    assessment: {
      id: number
      skillsVerified: string[]
      strengths: string
      summary: string
      publishedAt: Date | null
    }
    assessorName: string
  }[]
  exchanges: { talentTeaches: string; recruiterTeaches: string }[]
  steps: { videoChat: boolean; questionnaire: boolean; inHouseVisit: boolean }
  counts: { exchanges: number; meetings: number; questionnaires: number }
  videoIntro: { durationSec: number } | null
  generatedAt: Date
}

export default function RecordDocument({
  record,
  embedVideo = false,
}: {
  record: RecordData
  embedVideo?: boolean
}) {
  const { talent, match, verified, exchanges, steps, counts, videoIntro } = record
  const allVerifiedSkills = [...new Set(verified.flatMap((v) => v.assessment.skillsVerified))]
  const firstName = talent.name.split(' ')[0]

  return (
    <div className="record-doc overflow-hidden rounded-3xl border border-border bg-card shadow-xl">
      {/* HEADER */}
      <div className="relative bg-secondary px-7 py-8 text-secondary-foreground sm:px-10">
        <div className="texture-dots absolute inset-0" />
        <div className="relative flex flex-wrap items-center gap-5">
          <Avatar name={talent.name} gradient={talent.gradient} size="lg" />
          <div className="min-w-0 flex-1">
            <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-primary">
              <ShieldCheck className="h-4 w-4" /> NetWorthy Verified Record
            </div>
            <h1 className="mt-1.5 font-display text-3xl font-semibold sm:text-4xl">{talent.name}</h1>
            <div className="mt-1 text-secondary-foreground/75">
              {talent.role} — for <strong className="text-secondary-foreground">{match.role}</strong> at {match.company}
            </div>
          </div>
          <div className="rounded-2xl border border-white/15 bg-white/5 px-4 py-3 text-center">
            <div className="font-display text-xl font-semibold text-primary">{verified.length + counts.exchanges + 3}</div>
            <div className="text-[11px] font-semibold uppercase tracking-wider text-secondary-foreground/60">human verifications</div>
          </div>
        </div>
      </div>

      <div className="space-y-8 px-7 py-8 sm:px-10">
        {/* IN THEIR OWN WORDS */}
        <section>
          <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-muted-foreground">
            <Quote className="h-4 w-4" /> In their own words
          </div>
          <p className="mt-3 border-l-4 border-primary/30 pl-4 text-[15px] leading-relaxed text-foreground/90">
            {talent.story.length > 420 ? `${talent.story.slice(0, 420)}…` : talent.story}
          </p>
        </section>

        {/* VERIFIED SKILLS — the lead, not the appendix */}
        <section>
          <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-muted-foreground">
            <BadgeCheck className="h-4 w-4" /> Verified skills — confirmed by independent professionals
          </div>
          {verified.length > 0 ? (
            <>
              <div className="mt-3 flex flex-wrap gap-2">
                {allVerifiedSkills.map((s) => (
                  <span key={s} className="inline-flex items-center gap-1.5 rounded-full bg-emerald-100 px-3.5 py-1.5 text-sm font-semibold text-emerald-800">
                    <CheckCircle2 className="h-3.5 w-3.5" /> {s}
                  </span>
                ))}
              </div>
              <div className="mt-4 space-y-3">
                {verified.map(({ assessment: a, assessorName }) => (
                  <div key={a.id} className="rounded-2xl border border-emerald-100 bg-emerald-50/50 p-4">
                    <div className="text-sm font-semibold text-emerald-800">
                      {assessorName} · independent assessor, bound by confidentiality
                    </div>
                    <p className="mt-1.5 text-sm leading-relaxed text-foreground/85">{a.summary}</p>
                    <p className="mt-1.5 text-sm leading-relaxed text-muted-foreground">
                      <span className="font-semibold">Standout strengths:</span> {a.strengths}
                    </p>
                  </div>
                ))}
              </div>
            </>
          ) : (
            <p className="mt-3 text-sm text-muted-foreground">
              Independent assessment in progress — skills below are self-described, connection-verified.
            </p>
          )}
        </section>

        {/* THE CONNECTION THAT PROVED IT — the process IS the credential */}
        <section>
          <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-muted-foreground">
            <ShieldCheck className="h-4 w-4" /> The connection that proved it
          </div>
          <div className="mt-3 grid gap-3 sm:grid-cols-3">
            <div className="flex items-center gap-2.5 rounded-2xl border border-border p-3.5">
              <Video className="h-5 w-5 shrink-0 text-primary" />
              <div className="text-sm font-semibold">Video chat<span className="block text-xs font-medium text-muted-foreground">real conversation, before anything else</span></div>
            </div>
            <div className="flex items-center gap-2.5 rounded-2xl border border-border p-3.5">
              <ClipboardList className="h-5 w-5 shrink-0 text-primary" />
              <div className="text-sm font-semibold">Questionnaire{steps.questionnaire && <span className="block text-xs font-medium text-muted-foreground">{counts.questionnaires} completed, own words</span>}</div>
            </div>
            <div className="flex items-center gap-2.5 rounded-2xl border border-border p-3.5">
              <Building2 className="h-5 w-5 shrink-0 text-primary" />
              <div className="text-sm font-semibold">In-house visit<span className="block text-xs font-medium text-muted-foreground">met the team, saw the work</span></div>
            </div>
          </div>
          {counts.exchanges > 0 && (
            <div className="mt-3 rounded-2xl border border-border p-4">
              <div className="flex items-center gap-2 text-sm font-semibold">
                <ArrowRightLeft className="h-4.5 w-4.5 text-accent" />
                Teach &amp; Learn — {counts.exchanges} mutual exchange{counts.exchanges > 1 ? 's' : ''} completed
              </div>
              <div className="mt-2 space-y-1.5">
                {exchanges.slice(0, 3).map((e, i) => (
                  <div key={i} className="text-xs leading-relaxed text-muted-foreground">
                    <span className="font-semibold text-foreground/80">{firstName} taught:</span> {e.talentTeaches}
                  </div>
                ))}
              </div>
            </div>
          )}
        </section>

        {/* VIDEO INTRO */}
        <section>
          <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-muted-foreground">
            <Play className="h-4 w-4" /> Video introduction
          </div>
          {videoIntro ? (
            embedVideo ? (
              <video src={`/api/video-intro/${talent.id}`} controls playsInline className="mt-3 w-full rounded-2xl bg-black" />
            ) : (
              <p className="mt-3 text-sm text-muted-foreground">
                {firstName} recorded a {videoIntro.durationSec}-second introduction in their own words — available on the NetWorthy platform.
              </p>
            )
          ) : (
            <p className="mt-3 text-sm text-muted-foreground">A live video chat can be scheduled on the NetWorthy platform.</p>
          )}
        </section>

        {/* APPENDIX: context, not credentials */}
        <section className="rounded-2xl border border-dashed border-border bg-muted/40 p-5">
          <div className="text-xs font-bold uppercase tracking-widest text-muted-foreground">
            Appendix — context, not credentials
          </div>
          <div className="mt-3 flex flex-wrap gap-x-8 gap-y-2 text-sm text-muted-foreground">
            <span className="inline-flex items-center gap-1.5"><MapPin className="h-4 w-4" /> Originally from {talent.origin}</span>
            <span className="inline-flex items-center gap-1.5"><Clock className="h-4 w-4" /> {talent.yearsInNL} years in the Netherlands</span>
            <span className="inline-flex items-center gap-1.5"><Languages className="h-4 w-4" /> {talent.languages.join(', ')}</span>
          </div>
        </section>

        {/* FOOTER */}
        <footer className="border-t border-border pt-5 text-center">
          <p className="text-sm font-semibold text-foreground/80">
            Generated by NetWorthy from verified human connection — never self-reported.
          </p>
          <p className="mt-1 text-xs text-muted-foreground">
            This person was hired on connection before this document existed · networthy.app · {new Date(record.generatedAt).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}
          </p>
        </footer>
      </div>
    </div>
  )
}
